#!/usr/bin/python3

import math
from tools.eratos_sieve import eratos_sieve

def main(max_range):
    a_list = range(-max_range, max_range+1)
    b_list = eratos_sieve(max_range)

    max_sequence = 0
    max_a = 0
    max_b = 0
    for a in a_list:
        for b in b_list:
            n = count_primes(a, b)
            if n > max_sequence:
                max_sequence = n
                max_a = a
                max_b = b

    print("The solution is {}, in which a={} and b={} in a range between {} and {}; resulting in sequence of {} primes generated by n^2+an+b.".format(max_a*max_b, max_a, max_b, -max_range, max_range, max_sequence))
    return

def is_prime(n):
    if n < 2:
        return False
    if n < 4:
        return True
    if n % 2 == 0:
        return False
    if n < 9:
        return True
    if n % 3 == 0:
        return False
    
    r = math.floor(math.sqrt(n))
    f = 5
    while f <= r:
        if n % f == 0:
            return False
        if n % (f+2) == 0:
            return False
        f += 6
    
    return True

def count_primes(a, b):
    n = 0
    while is_prime((n*n)+(a*n)+(b)):
        n += 1
    return n

if __name__ == '__main__':
    main(2000)
